# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libassimp

# >> macros
# << macros

Summary:    Asset Import Library
Version:    0.0.1
Release:    1
Group:      Graphics
License:    BSD
URL:        https://github.com/assimp/assimp
Source0:    libassimp-%version.tar.gz
Source100:  libassimp.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake
BuildRequires:  cmake

%description
%{summary}.

%package devel
Summary:    Devel files
Group:      Graphics
Requires:   %{name} = %{version}-%{release}

%description devel
%{summary}.

%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre

%cmake . 
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libassimp.so.3
%{_libdir}/libassimp.so.3.0.1
%{_bindir}/assimp
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_libdir}/cmake/assimp-3.0/
%{_includedir}/assimp
%{_libdir}/libassimp.so
%{_libdir}/pkgconfig/assimp.pc
# >> files devel
# << files devel
